### ISSUE TITLE
Clarify distinction between this library and esri-loader

### ISSUE THREAD

**Issue by tomwayson** [nicksenger/esri-promise#1]
Nice work @nicksenger!

I really like the idea of having bootstrap take an optional argument to set the Dojo config, and may need to ~~steal~~ add that to esri-loader. 😉 

I would suggest adding some text to the the README explaining when you would use this library versus esri-loader. As far as I can tell the main distinction is that this exposes a promise-based API whereas esri-loader's uses callbacks. Beyond that (and the above mentioned Dojo config options), are there other distinctions I'm missing or that you are planning?

If esri-loader is missing features that you'd like to see, I welcome you suggestions and/or PRs.

**Comment by nicksenger** [comment]
Hi @tomwayson , thanks a lot for all your work on esri-loader and for clarifying a lot of the confusion surrounding the dojo loader in general.

As to the differences between this and esri-loader, originally I made this package to support [react-arcgis](https://github.com/nicksenger/react-arcgis), and anticipated that it may diverge from esri-loader more as that package continued to evolve. Really it seems like the only thing I ended up adding is the dojo config stuff though, so it is still pretty much 95% the same as esri-loader.

I figured that es6 promises would provide a more familiar syntax for react users, but in retrospect I worry that they create some unnecessary confusion since most of the asynchronous operations from the JS API use dojo/deferred.

If you do decide to add something to esri-loader to modify the dojo config, I may consider just moving react-arcgis to esri-loader, since there's not really any great reason to maintain this separately.

**Comment by tomwayson** [comment]
@nicksenger I've opened https://github.com/Esri/esri-loader/issues/39 and will be working on esri-loader over the next couple weeks so should have it implemented soon along with https://github.com/Esri/esri-loader/issues/8 or at least https://github.com/Esri/esri-loader/issues/30. I think if I can meet the requirements of your app, it will be useful for many others as well.

**Comment by nicksenger** [comment]
@tomwayson, sounds good!

I'm looking to trim the scope of react-arcgis down to just the maps/views, and encourage users to interact directly with the js api for anything beyond those constructs using something like esri-loader.

I see people trying to use the react wrapper for things that are best done directly on the api instances. Often I think this results from confusion about how to use the js api's module system from their non-amd apps, so hopefully narrowing things down will help lead users in the right direction.

**Comment by nicksenger** [comment]
@tomwayson thanks for adding those changes to esri-loader. I've deprecated this package and am currently porting react-arcgis to esri-loader.

**Comment by nicksenger** [comment]
@tomwayson thanks for adding those changes to esri-loader. I've deprecated this package and am currently porting react-arcgis to esri-loader.

**Comment by nicksenger** [comment]
@tomwayson thanks for adding those changes to esri-loader. I've deprecated this package and am currently porting react-arcgis to esri-loader.

**Comment by tomwayson** [comment]
esri-loader [v1.5](https://github.com/Esri/esri-loader/releases/tag/v1.5.0) has been released w/ the new promise-based API.

Give it a whirl in react-arcgis and let me know how it works for you. I've [updated ember-esri-loader to use it](https://github.com/Esri/ember-esri-loader/pull/36), and it [seems to be working out great](http://ember-esri-loader.surge.sh/).

**Comment by tomwayson** [comment]
FYI - [esri-loader@2.0.0](https://github.com/Esri/esri-loader/releases/tag/v2.0.0) is now out, which drops the old callback-based baggage. I have that working in Ember, React, and Vue.js example apps.

At this point, I'm not totally clear on the distinctions between the libraries (since each has borrowed so many ideas from the other). Here's my take on what is unique about each:

esri-promise:
- will (console) warn you if try to overwrite an existing require implementation.

esri-loader:
- `loadModules()` (equivalent to `esriPromise()`) can take the `url` and `dojoConfig` as options - ideally you don't need to use `loadScript()` (equivalent to `esriBootstrap()`) unless you're explicitly preloading the script
- `loadModules()` also checks if the JSAPI is in the process of loading (not just if it has already loaded) and if so will wait until it loads before loading the modules
- defaults to v4.6

Did I miss anything?

**Comment by nicksenger** [comment]
@tomwayson yep that looks about right to me. The libraries are pretty much redundant at this point. I wont be maintaining esri-promise anymore for this reason.

**Comment by nicksenger** [comment]
alright @tomwayson, I've moved [react-arcgis](https://github.com/nicksenger/react-arcgis) over to [esri-loader](https://github.com/Esri/esri-loader) and deprecated this package on npm.

Hopefully soon we wont need any of these integration libs, we'll see :]
